### ISSUE TITLE
Hickle not working with h5py 3.0

### ISSUE THREAD

**Issue by cyfra** [telegraphic/hickle#143] opened 2020-11-02 12:34 UTC
Hickle seems to stop working with h5py 3.0.0. It works fine with 2.10.

Example code:
```
import hickle as hkl

hkl.dump([1,2,3], "/tmp/foo.hkl")
hkl.load("/tmp/foo.hkl")
```

Fails with 
```
ValueError: Provided argument 'file_obj' does not appear to be a valid hickle file! (Cannot load <HDF5 dataset "data": shape (3,), type "<i8"> data type)
```

**Comment by 1313e** [comment] 2020-11-03 11:47
Hi @cyfra,

we need a bit more information than that.
For example, what version of `hickle` are you using?

**Comment by 1313e** [comment] 2020-11-04 01:15
Alright, I found the issue.
In `h5py` 3.0, strings stored in HDF5-files are now returned as unicode rather than bytes.
This would require changing all places where strings are being read in to function properly.

@telegraphic I think the best option for now is to exclude `h5py` 3.x from the requirements until they have released a few versions of it.
Besides writing a function that checks what version of `h5py` you are using; uses the proper method of reading strings; and applying it literally everywhere where `hickle` reads strings, we cannot make a compatibility change for this.
Forcing everyone to upgrade to `h5py` 3.0 right now, feels like a bit too much to me.

**Comment by cyfra** [comment] 2020-11-07 14:14
@1313e  - thanks a lot for looking into this so quickly.

**Comment by hernot** [comment] 2020-12-12 12:11
@1313e @telegraphic 
Since a while ago i got in contact with [tox](https://tox.readthedocs.io/en/latest/index.html) package on another project I'm contributing to and i have to admit i like it. Therefore i was curious whether it would be possible to simplify maintaining production release while at the same time in parallel work on another branch on eg. issues arising when wanting to support h5py. 2.X versions in parallel to recent 3.0 and future 3.X versions. The results of this curiosity can be found in the detached  [concept_memp_compact_expand](https://github.com/hernot/hickle/tree/concept_memp_compact_expand) branch of my hickle fork. Be warned the only test working therein is the test_stateful.py for which at least one > 100 MB file is required i have to share with you via file-sharing service as github does not allow to link forked repos with git(hub) large file service. Further even though i have edited .travis.yaml and .appveyor.yaml according to documentation to be aware of running tests through tox instead of directly calling pytest i have, thanks to the other project some idea about travis but none about appveyor, if that works as intended or at all. Never the less i wanted to let you know about.

**Comment by 1313e** [comment] 2020-12-17 01:17
Alright, given that I have had very little time lately to do things, I am just removing `h5py` 3.x from the requirements for now.

**Comment by hernot** [comment] 2020-12-20 21:32
This is the only one where i just have as a by product of compression safety proofing an unfinished and to further discuss and extend suggestion, which will be included in finalize and clean up pull-request.

**Comment by hernot** [comment] 2021-01-01 20:54
Ok one issue which will definitely will persist even after memoisation implementation is the fact that h5py >= 3.0 converts all `bytes` strings like 'item_type' which were assigned to an attribute to a `str` assuming that they were created form python2 strings or are just manually encoded python3 `str` objects. The only option i have found to enforce creating an `bytes` type attribute is to use the `create` method of the `attrs` property  this allows to explicitly specify the dtype of the attribute 

```
some_dataset_or_group.attrs.create('item_type',data=b'str',dtype = 'S{}'.format(len(b'str')))
print(some_dataset_or_group.attrs['item_type'],type(some_dataset_or_group.attrs['item_type']))
print(some_dataset_or_group.attrs.get('item_type'),type(some_dataset_or_group.get('item_type')))
```
Alternatively just support h5py >= 3 in newer version of hickle and sacrifice support of h5py < 3 which I'm not sure if this is currently an option. Just as a side node with type memoisation in place this will not be an issue for 'type' and 'base' type attributes. But reading older files will be impossible with hickle versions upporting h5py >= 3 as pickle string will cause encoding errors when h5py tries to convert them to utf8 used by str.

Not yet seen reported issue from unit tests as added by pr #138. keep you posted as i also would be interested in using hickle on newer systems where h5py >= 3 is already installed and switching back to h5py < 3 is no option.

**Comment by peendebak** [comment] 2021-08-02 12:40
@hernot Any update on this issue? h5py < 3.x is not providing wheels for python 3.9 on windows, so this blocks hickle on python 3.9

**Comment by hernot** [comment] 2021-08-03 16:30
### The Situation is:
From Python 3.9 on only h5py >= 3.x and that is 64 bit only. In addition manual compilation and installation via pip will also fail, cause h5py >= 3.x requires libhdf5 versions which are too available 64bit only.

### The status of hickle as far as I'm involved is:
Forthcomming hickle >= 5.x, currently reviewed by @1313e  and @telegraphic, will support h5py >=3.x. From Python 3.9 support 64bit is the only option. On Python < 3.9 it will fallback to h5py 2.10. 

@1313e  are there any plans for hickle 4.x to backport the requirements?

**Comment by 1313e** [comment] 2021-08-04 00:59
@peendebak @hernot Yeah, I think we should backport this to `hickle` v4.
I am currently in the process of moving back to my home country, but I should have time to do that afterward.
So, I hope you can wait for a few weeks, as it isn't a very trivial process.
Unelss you want to give a go yourself of course.

**Comment by hernot** [comment] 2021-08-04 07:11
@peendebak if you are intending to help in backport i can help and share my knowledge related to the topic i gained through preparation of hickle 5 release candidate.
@1313e on atempting to backport shoud than hickle 4 also switched from travis and appveyor to gh actions ?

**Comment by 1313e** [comment] 2021-08-04 08:09
@hernot Probably, yes.
Moving away entirely from Travis CI and Appveyor would be really great.

**Closed** 2021-12-19 01:39 UTC
