### ISSUE TITLE
Conda Verison Of Hickle Hasn't Been Updated Since 2019 (v3.4.5)

### ISSUE THREAD

**Issue by Stargrazer82301** [telegraphic/hickle#177] opened 2024-02-06 16:43 UTC
As said in title: the conda-forge version of hickle, v3.4.5, dates from 2019, and has some Python 3 incompatibilities.

I was having some trouble getting hickle to work (getting the error "string argument without an encoding" when trying to read in a hickle file I'd just made). After some googling, I saw that this problem was fixed in version 5. I checked my version, and saw that I only had version 3.4.5! I tried updating in conda/mamba, but it told me I had the newest version.

I'd really rather avoid installing via pip; I have been clobbered by mixed-up pip+conda environments too many times!

**Comment by telegraphic** [comment] 2024-03-30 08:58
Agreed, I might need some help with conda-forge though to make this happen. Marking as duplicate of #168

**Closed by telegraphic** 2024-03-30 08:58 UTC
