### ISSUE TITLE
Dictionary keys with a backslash

### ISSUE THREAD

**Issue by fleming79** [telegraphic/hickle#16] opened 2015-03-04 06:58 UTC
HDF5 format uses the backslash to identify a collection so if a backslash is encountered from a mappable object then the backslash will cause the creation of a collection instead of escaping the backslash. Maybe you can replace the backslash with some sort of 'key' like \backslash while packing, which you could then replace with the symbol '/' on reconstruction?

**Comment by telegraphic** [comment] 2015-03-06 03:28
Hmm, I'm not sure about this one as it's unclear what most people would expect to happen: people familiar with HDF5 would probably expect nested groups, and others may not. So it might result in unexpected behavior if we're not careful.

Can I get please get a bit more info on the use case of this? E.g. in what circumstances would a dictionary key have a backslash in it where creating nested groups would not be desirable?

**Comment by fleming79** [comment] 2015-03-06 09:13
I don't think so. If you pack and unpack using hickle you should expect the
same structure. I was using units. Like m/s this will nest s in m. Which is
not what was intended. I can see your point of view but was surprised by
this since I'm not that familiar with hdf5. Thanks for considering, since
I've become aware of this issue I've stopped using a forward slash.

On 06/03/2015 2:28 PM, "Danny Price" <notifications@github.com> wrote:

Hmm, I'm not sure about this one as it's unclear what most people would
expect to happen: people familiar with HDF5 would probably expect nested
groups, and others may not. So it might result in unexpected behavior if
we're not careful.

Can I get please get a bit more info on the use case of this? E.g. in what
circumstances would a dictionary key have a backslash in it where creating
nested groups would not be desirable?

—
Reply to this email directly or view it on GitHub
<https://github.com/telegraphic/hickle/issues/16#issuecomment-77500788>.

**Comment by telegraphic** [comment] 2015-03-13 16:20
OK, I see the use case now, and agree that "pickle-like" functionality is more important than "hdf-like" functionality (particularly given the name :wink:). So next chance I get I'll add this in.

**Comment by telegraphic** [comment] 2017-01-03 10:42
After some research and thought, I am closing this issue for now. Given the [HDF5 link name definition](http://davis.lbl.gov/Manuals/HDF5-1.8.7/UG/09_Groups.html), this would be pretty hard to implement:

> Link names may be any string of ASCII or UTF-8 characters that do not contain a slash or a dot. These are reserved as noted above. However, users are advised to avoid the use of punctuation and non-printing characters in link names: these may create problems for other software.

The only two ways I see of implementing this are:

1) Replace slashes with a rarely used UTF symbol
2) Replace the group name with a stand-in, and then have the requisite name in an attribute.

Both of these are messy in terms of data model and non-desirable. So I am chalking this up as a limitation of hickle/hdf5.

**Closed** 2017-01-03 10:42 UTC
Labels: wontfix

**Comment by wangqr** [comment] 2019-04-28 02:32
Can hickle give some warning or error when dumping a dictionary that contains slash in its key?

I found this issue because I dumped a dict with keys `'fc1/w'`, `'fc1/b'`, etc. without problem and then found that I am unable to load the dumped file.
